master:
  node_id: 2
  sync_period: 20000 # set syn period to 50 ms

trinamic_pd42:
  node_id: 1
  dcf: "TMCM-1270.eds"
  driver: "ros2_canopen::MotionControllerDriver"
  package: "motion_controller_driver"
  sdo: # SDO executed during config
  - {index: 0x6081, sub_index: 0, value: 500000} # Set velocity
  - {index: 0x6083, sub_index: 0, value: 1000000} # Set acceleration
  - {index: 0x6083, sub_index: 0, value: 1000000} # Set deceleration
  - {index: 0x6085, sub_index: 0, value: 1000000} # Set quickstop deceleration
  - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
  - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
  - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6061, sub_index: 0} # mode of operaiton display
    2:
      enabled: true
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0} # position actual value
        - {index: 0x606c, sub_index: 0} # velocity actual position
    3:
      enabled: false
    4:
      enabled: false
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      mapping:
      - {index: 0x607A, sub_index: 0} # target position
      - {index: 0x60FF, sub_index: 0} # target velocity

  heartbeat_producer: 1000 # Heartbeat every 1000 ms